### ISSUE TITLE
Build error: Failed to collect page data 

### ISSUE THREAD

**Issue by buccalon** [samvera-labs/clover-iiif#91]
Hi @mathewjordan!

At [tiju.ca](https://tiju.ca) I am trying to make clover-iiif work with [nextra](https://nextra-v2-git-shu-ceb9-shuding1.vercel.app/) and [biiif](https://github.com/IIIF-Commons/biiif)

I got it working locally within [a markdown document](https://github.com/buccalon/tijuca/blob/main/pages/item/1891-relatorio-archer.md):

![Screen Shot 2022-09-10 at 22 46 48](https://user-images.githubusercontent.com/476699/189511605-8b2c059d-a96f-4c23-8775-ca6b92e9a428.png)

However, something breaks the build process at Vercel:

```
[22:35:29.342] Cloning github.com/buccalon/tijuca (Branch: main, Commit: 4283112)
[22:35:29.906] Cloning completed: 563.775ms
[22:35:30.470] Looking up build cache...
[22:35:32.777] Build cache downloaded [46.01 MB]: 1961.975ms
[22:35:32.824] Running "vercel build"
[22:35:33.328] Vercel CLI 28.2.2
[22:35:33.692] Installing dependencies...
[22:35:34.245] Lockfile is up-to-date, resolution step is skipped
[22:35:34.272] Progress: resolved 1, reused 0, downloaded 0, added 0
[22:35:34.362] Packages: +90
[22:35:34.362] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[22:35:35.273] Progress: resolved 90, reused 0, downloaded 31, added 35
[22:35:36.274] Progress: resolved 90, reused 0, downloaded 75, added 86
[22:35:36.750] 
[22:35:36.750] dependencies:
[22:35:36.750] + @samvera/clover-iiif 1.10.3
[22:35:36.750] 
[22:35:37.274] Progress: resolved 90, reused 0, downloaded 79, added 90, done
[22:35:37.293] Detected Next.js version: 12.3.0
[22:35:37.300] Running "pnpm run build"
[22:35:37.783] 
[22:35:37.783] > tiju.ca@0.0.1 build /vercel/path0
[22:35:37.783] > next build
[22:35:37.783] 
[22:35:38.346] info  - Linting and checking validity of types...
[22:35:38.555] info  - Creating an optimized production build...
[22:35:40.094] [nextra] The repository is shallow cloned, so the latest modified time will not be presented. Set the VERCEL_DEEP_CLONE=true environment variable to enable deep cloning.
[22:35:47.703] 
[22:35:47.704] [1m[33mwarn[39m[22m - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
[22:35:47.705] [1m[33mwarn[39m[22m - https://tailwindcss.com/docs/content-configuration
[22:35:58.888] info  - Compiled successfully
[22:35:58.888] info  - Collecting page data...
[22:35:59.481] ReferenceError: document is not defined
[22:35:59.481]     at /vercel/path0/node_modules/.pnpm/openseadragon@3.1.0/node_modules/openseadragon/build/openseadragon/openseadragon.js:945:29
[22:35:59.482]     at /vercel/path0/node_modules/.pnpm/openseadragon@3.1.0/node_modules/openseadragon/build/openseadragon/openseadragon.js:948:6
[22:35:59.482]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/openseadragon@3.1.0/node_modules/openseadragon/build/openseadragon/openseadragon.js:1046:2)
[22:35:59.482]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[22:35:59.482]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[22:35:59.482]     at Module.load (node:internal/modules/cjs/loader:981:32)
[22:35:59.482]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[22:35:59.483]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[22:35:59.483]     at require (node:internal/modules/cjs/helpers:102:18)
[22:35:59.483]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/@samvera+clover-iiif@1.10.3/node_modules/@samvera/clover-iiif/dist/index.cjs.js:1:80661)
[22:35:59.483] 
[22:35:59.484] > Build error occurred
[22:35:59.485] Error: Failed to collect page data for /item/1891-relatorio-archer
[22:35:59.486]     at /vercel/path0/node_modules/.pnpm/next@12.3.0_react-dom@17.0.2+react@17.0.2/node_modules/next/dist/build/utils.js:771:15
[22:35:59.486]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[22:35:59.486]   type: 'Error'
[22:35:59.486] }
[22:35:59.512]  ELIFECYCLE  Command failed with exit code 1.
[22:35:59.522] Error: Command "pnpm run build" exited with 1
```

Do you have any suggestions on how should I proceed?

Thanks again :)

**Comment by mathewjordan** [comment]
Hi@buccalon, The `ReferenceError: document is not defined` error I believe is the ultimate source issue here. The depedency for OpenSeadragon expects the browser `document` to exist and doesn't play well in a node environment. When Next is building its trying to render OpenSeadragon and then crashing...

There is a solution though, but it must be done through a dynamic import package in `next/dynamic`

1) I suggest creating a component the side that can operate outside of your Markdown pages.

`components/IIIFViewer.jsx`

and in that...

```
import dynamic from "next/dynamic";

const CloverIIIF = dynamic(() => import("@samvera/clover-iiif"), {
  ssr: false,
});

const IIIFViewer = ({ id }) => {
  return <CloverIIIF id={id} />;
};

export default IIIFViewer;
```

2) Then in each of your markdown files...

```
import IIIFViewer from '../../Components/IIIFViewer'

# Relatório dos trabalhos executados na Floresta Nacional da Tijuca de 1º de Janeiro a 31 de Dezembro de 1890, por Manuel Gomes Archer

<IIIFViewer id="https://iiif.tiju.ca/1891-relatorio-archer" />

## Contexto
...
```

Let me know if that helps. Best - Mat

**Comment by buccalon** [comment]
@mathewjordan thanks for taking the time and updating the docs, it worked!

![image](https://user-images.githubusercontent.com/476699/190561119-9fdc5095-5849-4e0c-be4c-f65fb3e2e479.png)
